### ISSUE TITLE
"You do not have permission to open the application “Waterlooplein3D.app”." on Big Sur

### ISSUE THREAD

**Issue by hay** [ElmarJ/Waterlooplein3D#86]
I tried downloading the v2 Mac app, but it seems it unfortunately doesn't work. I'm getting the error "You do not have permission to open the application “Waterlooplein3D.app”.". When trying to run this in a terminal (using the `open` command), i'm getting the error:

`The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x12c108e50 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x12c107ae0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}`

I've googled that error and this might be because of stricter security rules in macOS Big Sur (v11.2), but i'm also using an Apple Silicon (M1) machine which might be the cause of the problem.

If i have some time i might try loading up the repo in Unity and try if i can compile a compatible version from there.

**Comment by ElmarJ** [comment]
Thanks for the report! I don't have a Mac myself, so I can't test, but the problem seems to be related to building a Mac-executable on a Windows PC (and indeed the resulting security permissions). See also https://forum.unity.com/threads/issue-opening-unity-mac-applications-on-mac-big-sur-os-from-unidentified-developer.1026697/#post-6650740 . There is a workarround mentioned there, I guess that this should work:

```
chmod +x "Waterlooplein3D.app/Contents/MacOS/Waterlooplein 3D"
xattr -r -d com.apple.quarantine Waterlooplein3D.app/
```
I'm working on a new release pipeline using cloud builds (using a linux image), hopefully that should solve the issue....

**Comment by hay** [comment]
Hey, that worked! Had no trouble at all running the demo on normal quality in 1920x1080 on my MacBook Air. Thanks!
